language: node_js
branches:
  only:
  - master
  - dev
node_js:
- stable
after_success: npm run coverage && ./scripts/merge_dev_with_master.sh
sudo: false
deploy:
  provider: heroku
  app: offshop-back-end
  on: master
  api_key:
    secure: hP33KqW0ZfX0ASdy8OSJpnd/vLoWON2Gym8I8sCcF2Nk0wFjoXfEBqR0UXQMN3dExNjfVILQajY1rKEY4gIl+bc1sqPeqTGRf+UTwMkFbfDagmpGAcxfPcusZ5723y1RCUPhsJrF7erAzKDwpLpceCgWEp6sEb9QZ+ujIl14AHk6KJL2f0f9zQDPa9bnbJ731ls8nG3sj5KjdQRoiTtUKewH3ii2JHtpG5gaKDQgT8PW/FjbW5Wjr1CThLw3Q4p5tzqMksXEO4GnXTYSRVcMAZEEB4MOHH7TInbXFWiVLwhbNo9b62n5G7oDukK7n8D2wfQ6aSqMVDEy2H9BAPzMv4VPfB3I96PPzKsezkXgUys1H8eLlEKoMoYeqd4P8y8puzC74U+8OrlbspUIM3CAq/tmLrmsUeftPKyNabyDJtmojQWWGPkLsP3XKuezf2WT9/d+V7kZnBUfMVVTypj1gro/URfvLTFv+s5k3r8yALd+Cr2FMLkiZiXjalUFvPpvTK6FZKCuel5QBOAJPEGKe1ZKuwXkCl6hFEqmKR0Yd4VEu7DeBA9BgkE7jnbyQFdbsiP2zYCnWbL6crXnwjh1U5WdICRMvZmptK/fjTzl2867KI59o1Olcn85dSNCsdGuRqFDfvKAra45HryoXphkTIbdN4vYmSImn++FBxZ2ub4=
env:
  global:
    secure: ScfQ8cJAy1CwfOlVToSG92By4zSKhh0yeNoJAcjLecHVTTvo7HD7r5fJ5wK0cI4Wl1sWOnJ0RSksWfiEb2+jehEwdUiuxL8rmtiLR1iPy93KkCtgkzPjJlpi1nF/uhppHFvXti2iGThkeuw3x521f/mYaOW0t4wW24ue3T3vkk7OholOCYdelsvaflZuVjac5sj7i4WjDJ9gquR1OxJh8yz9+iONQIIckeIPHi8xVe2dsMuUtWmvIAsKs98PqSi4VrpY6a94DS8r++fRSdNU/PzVvv8UJePuqhXSBHtqU94OkGXN0vnumDc5NSZERBTi/UEL1HF3Yb/OEHhZUDwz7bsHx18J/EliMp2NmX2izZIxwBD72fEtn21mf0jJOmSlqdZG4qpL10oZpMe09kqrd1zysXwsEN5u6MCxEctrj++vp5npzFO/heUB+hP1Lxxwxqb4syoxgVl04Qb1TYDabS6obNp1fHB35xycix6eITomW+ZpG1KsQn8RhIqKFodNXOPDBW0xHr0JKO7vEydUsU/2KdEUKRrTI0we6bxFrjv28FifxqdkJwZobxT9tlj57QQNcsomFUzAKFZrzJuIESM2OfSMeqhiHDcv8OB4nw0yv68m0txW95yF3NHJSg16Am+s/6HK8foLenG0bvTFnT8xljT+H/iKs1N3B/JebYY=
