language: node_js
branches:
  only:
  - master
  - dev
node_js:
- stable
after_success: "npm run coverage && ./scripts/merge_dev_with_master.sh"
sudo: false
deploy:
  provider: heroku
  app: offshop-back-end
  on: master
  api_key:
    secure: DmRPenxmXk6T5ucokem+WkIIrexPcyIXGN13xX2G2aiMO29GEjWC3yVyaixx9Q7K+yjkkANVtgoLyaGkRNVv8+bKJaaww8wRPKbzp03QJIPK5sXdclae7rMfMq5G0rln5ZafUcfRb4BLjuma0eIPXQiZTIbSb5lzlgp8VewuQvEaAPbLC7UvvDkTfVmck7YhNsd3QqqzAYy8cutfhVvNnaCP7X25DhE6J3ePYboFz/3ve/Qmlq0feok2eVP2bXcLNWRbJ1ep6gQeWIn6x0H5RlJVAhxcbr3cxodO7qrtzdEhIKm+qvE115Htj+n6nVNa0T+ztrXy3CJNHNfZkhn6n/UVcfTNwZHF4j8r81RqezJh2ORdTwUaWV1DaOZTlkfXrVbyJVoEqhRCm2LvpJgyvOPgJF2PG7lyCM6OCIVy4zSRfdSGVCTlbx3x/VbPapEfjZOBfmgZl6Uts6DLTRfBvIuaXD6uuZy2hBFU7ETMyf1MgkeqfpyaFd9k4UKlc0lA6GF5LEysDw9v2bXXs/bzxkSmv7pZP9yXcVTDys4ir3dU4SR1UQ7kocGxSmIB+uvDD9tyFavweuwPnKDCf6XQt7rDq5ysPDd4tkAiOI92dStpu/uecHnD6Z/zCS6iz4CFzF9rHafaZg5VC+ntFFzuhE1xlCvdsE228Yb4MoUlWUs=
env:
  global:
    secure: ScfQ8cJAy1CwfOlVToSG92By4zSKhh0yeNoJAcjLecHVTTvo7HD7r5fJ5wK0cI4Wl1sWOnJ0RSksWfiEb2+jehEwdUiuxL8rmtiLR1iPy93KkCtgkzPjJlpi1nF/uhppHFvXti2iGThkeuw3x521f/mYaOW0t4wW24ue3T3vkk7OholOCYdelsvaflZuVjac5sj7i4WjDJ9gquR1OxJh8yz9+iONQIIckeIPHi8xVe2dsMuUtWmvIAsKs98PqSi4VrpY6a94DS8r++fRSdNU/PzVvv8UJePuqhXSBHtqU94OkGXN0vnumDc5NSZERBTi/UEL1HF3Yb/OEHhZUDwz7bsHx18J/EliMp2NmX2izZIxwBD72fEtn21mf0jJOmSlqdZG4qpL10oZpMe09kqrd1zysXwsEN5u6MCxEctrj++vp5npzFO/heUB+hP1Lxxwxqb4syoxgVl04Qb1TYDabS6obNp1fHB35xycix6eITomW+ZpG1KsQn8RhIqKFodNXOPDBW0xHr0JKO7vEydUsU/2KdEUKRrTI0we6bxFrjv28FifxqdkJwZobxT9tlj57QQNcsomFUzAKFZrzJuIESM2OfSMeqhiHDcv8OB4nw0yv68m0txW95yF3NHJSg16Am+s/6HK8foLenG0bvTFnT8xljT+H/iKs1N3B/JebYY=
